{{ if not .Values.enterprise.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "smoke-test") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "smoke-test") | nindent 4 }}
  annotations:
    {{- if .Values.smoke_test.annotations }}
    {{- toYaml .Values.smoke_test.annotations | nindent 4 }}
    {{- end }}
    "helm.sh/hook": test
  namespace: {{ .Release.Namespace | quote }}
spec:
  backoffLimit: {{ .Values.smoke_test.backoffLimit }}
  completions: 1
  parallelism: 1
  selector:
  template:
    metadata:
      labels:
        {{- include "mimir.podLabels" (dict "ctx" . "component" "smoke-test") | nindent 8 }}
    spec:
      serviceAccountName: {{ template "mimir.serviceAccountName" . }}
      {{- if .Values.smoke_test.priorityClassName }}
      priorityClassName: {{ .Values.smoke_test.priorityClassName }}
      {{- end }}
      securityContext:
        {{- include "mimir.lib.podSecurityContext" (dict "ctx" . "component" "smoke-test") | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      initContainers:
        {{- toYaml .Values.smoke_test.initContainers | nindent 8 }}
      containers:
        - name: smoke-test
          image: {{ include "mimir.imageReference" (dict "ctx" . "component" "smoke-test") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=continuous-test"
            - "-activity-tracker.filepath="
            - "-tests.smoke-test"
            - "-tests.write-endpoint={{ default (include "mimir.gatewayUrl" .) .Values.smoke_test.write }}"
            - "-tests.read-endpoint={{ default (include "mimir.gatewayUrl" .) .Values.smoke_test.read }}/prometheus"
            - "-tests.tenant-id={{ .Values.smoke_test.tenantId }}"
            - "-tests.write-read-series-test.num-series=1000"
            - "-tests.write-read-series-test.max-query-age=48h"
            - "-server.http-listen-port={{ include "mimir.serverHttpListenPort" . }}"
            {{- if eq .Values.smoke_test.auth.type "tenantId" }}
            - "-tests.tenant-id={{ .Values.smoke_test.auth.tenant }}"            
            {{- end }}
            {{- if eq .Values.smoke_test.auth.type "basicAuth" }}
            - "-tests.basic-auth-password={{ .Values.smoke_test.auth.password }}"
            - "-tests.basic-auth-user={{ .Values.smoke_test.auth.tenant }}"
            {{- end }}
            {{- if eq .Values.smoke_test.auth.type "bearerToken" }}
            - "-tests.bearer-token={{ .Values.smoke_test.auth.bearerToken }}"
            {{- end }}
            {{- range $key, $value := .Values.smoke_test.extraArgs }}
            - -{{ $key }}={{ $value }}
            {{- end }}
          {{- if .Values.smoke_test.resources }}
          resources:
            {{ toYaml .Values.smoke_test.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.smoke_test.extraVolumeMounts }}
              {{ toYaml .Values.smoke_test.extraVolumeMounts | nindent 12 }}
            {{- end }}
            {{- if .Values.global.extraVolumeMounts }}
              {{ toYaml .Values.global.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- if or .Values.global.extraEnv .Values.smoke_test.env }}
          env:
            {{- with .Values.global.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.smoke_test.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if or .Values.global.extraEnvFrom .Values.smoke_test.extraEnvFrom }}
          envFrom:
            {{- with .Values.global.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.smoke_test.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      restartPolicy: OnFailure
      volumes:
        {{- if .Values.smoke_test.extraVolumes }}
        {{ toYaml .Values.smoke_test.extraVolumes | nindent 8 }}
        {{- end }}
        {{- if .Values.global.extraVolumes }}
        {{ toYaml .Values.global.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}
